source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'EasyZoom_Example', :exclusive => true do
  pod "EasyZoom", :path => "../EasyZoom.podspec"
end

target 'EasyZoom_Tests', :exclusive => true do
  pod "EasyZoom", :path => "../EasyZoom.podspec"
end
